export const DataPortofolio = [
  {
    image: 'personal-website',
    title: 'Personal Website v.1',
    category: 'Personal Challenge',
    description:
      'A personal website that explains how I love the world of frontend developer',
    stacks: ['Typescript', 'Next Js', 'React Js', 'Tailwind', 'Material UI'],
    github: 'https://github.com/ihsnmuh/story-ihsan',
    website: 'https://story-ihsan-ihsnmuh.vercel.app/',
  },
  {
    image: 'krealogi-case',
    title: 'Krealogi: UI/UX Challenge',
    category: 'UX/UI Challenge',
    description:
      'This project describes the features of marketplace and logistics integration.',
    stacks: ['Figma', 'UI', 'UX Case Study'],
    github: '',
    website:
      'https://ihsnmuh.medium.com/integrasi-logistik-expedisi-marketplace-pada-aplikasi-krealogi-ux-case-study-b52f5f9b4563',
  },
  {
    image: 'dashboard-mmp',
    title: 'Matamata Politik Dashboard',
    category: 'Internal Project',
    description:
      'This project was created to manage the news on the matamatapolitik.com website',
    stacks: ['Typescript', 'Next Js', 'React Js', 'Material UI', 'gRPC'],
    github: '',
    website: 'https://www.matamatapolitik.com',
  },
  {
    image: 'qurantara',
    title: 'Qurantara',
    category: 'Personal Challenge',
    description:
      'This website functions as a medium for reading and listening to the Quran, reading hadith, and also viewing prayer schedules based on regions',
    stacks: [
      'Javascript',
      'Vue Js',
      'Bootstrap',
      'Heroku',
      'Firebase',
      'Express Js',
      'Postgresql',
    ],
    github: 'https://github.com/ihsnmuh/qurantara-client',
    website: 'https://qurantara-30c57.web.app/',
  },
  {
    image: 'sugoku',
    title: 'Sugoku Mobile App',
    category: 'Personal Challenge',
    description:
      'Sugoku Mobile App is An interactive mobile game to play sudoku with 3 level difficulties',
    stacks: ['Javascript', 'Expo', 'React Native'],
    github: 'https://github.com/ihsnmuh/sugoku',
    website: 'https://expo.dev/@ihsnmuh/sugoku-ihsan',
  },
  {
    image: 'ecommerce-wannabe',
    title: 'E-Commerce Wannabe',
    category: 'Personal Challenge',
    description:
      'Like Web e-commerce in general, you can order some gadget and add to the cart, but this is very simple',
    stacks: [
      'Sequelize',
      'Express',
      'PostgreSQL',
      'Jest',
      'Vue Js',
      'Bootstrap',
      'Heroku',
      'Firebase',
    ],
    github: 'https://github.com/ihsnmuh/ecommerce-cms-client',
    website: 'https://ecommerce-client-mu.web.app/',
  },
  {
    image: 'kanban-mu',
    title: 'Kanban Mu',
    category: 'Personal Challenge',
    description:
      'Kanban mu is an application to managing tasks with many users',
    stacks: [
      'Sequelize',
      'Express',
      'PostgreSQL',
      'JWT',
      'Jest',
      'Vuejs',
      'Bootstrap',
      'Heroku',
      'Firebase',
      'Google Auth',
    ],
    github: 'https://github.com/ihsnmuh/kanban-client',
    website: 'https://kanban-mu.web.app/',
  },
  {
    image: 'fancy-todo',
    title: 'Fancy Todo',
    category: 'Personal Challenge',
    description:
      'Fancy Todo is an application for managing your to-do list with other users.',
    stacks: [
      'Sequelize',
      'Express',
      'PostgreSQL',
      'JWT',
      'Jquery',
      'Ajax',
      'Bootstrap',
      'Google Auth',
      'Heroku',
      'Firebase',
    ],
    github: 'https://github.com/ihsnmuh/fancy-todo-client',
    website: 'https://fancy-todosmu.web.app/',
  },
  {
    image: 'nonton-movies',
    title: 'Nonton Movies',
    category: 'Personal Challenge',
    description: 'Movie Web is a website to search popular Movie and Tv Series',
    stacks: ['Javascript', 'Firebase', 'React', 'Bootstrap'],
    github: '',
    website: 'https://nonton-moviesme.web.app/',
  },

  {
    image: 'entertain-me',
    title: 'Entertain Me',
    category: 'Personal Challenge',
    description:
      'EntertainMe is a mobile app for managing data movie and series',
    stacks: [
      'React Native',
      'Apollo',
      'GraphQL',
      'Expo',
      'Microservices',
      'MongoDB',
      'Express',
      'Redis',
      'AWS',
    ],
    github: 'https://github.com/ihsnmuh/entertainme',
    website: 'https://expo.dev/@ihsnmuh/entertaime-ihsan',
  },
];
